---
# Removes a volume from a volume collection
# $ ansible-playbook -e nimble_volume=myvol1 \
# sample_unprotect.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble, 
        nimble_object: volume,
        nimble_operation: unprotect
      }
