---
# Establish partnership with HPE Cloud Volumes
#
# $ ansible-playbook -e cloud_store_region \
# -e cloud_store=MyReplicationStore \
# sample_cloud_partner.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: cloud,
        nimble_operation: partner
      }
