---
# Updates the group options. The following example updates the DNS domain, DNS servers and sets
# a custom login banner message.
# $ ansible-playbook sample_group_update.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: group,
        nimble_operation: update,
        nimble_group_update: {
          domain_name: example.com,
          dns_servers: [
            { "ip_addr": "8.8.8.8" },
            { "ip_addr": "1.1.1.1" }
          ],
          login_banner_message:
            "This array is managed by Ansible. Configuration changes
            may be overridden periodically. Contact support@example.com
            for further information."
        }
      }
