---
# Establish partnership with HPE Cloud Volumes
#
# $ ansible-playbook -l limit -e cloud_store_region -e cloud_store=MyReplicationStore sample_cloud_partner.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: cloud,
        nimble_operation: partner
      }
