---
# Provide nimble_volume, nimble_volume_mountpoint and nimble_volume_snapshot as extra vars, i.e
# $ ansible-playbook -l limit -e nimble_volume=myvol1 -e nimble_volume_mountpoint=/mnt/myvol1 -e nimble_volume_snapshot=mysnap1 sample_restore.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: umount }
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: unmap }
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: restore }
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: map }
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: mount }
