---
# Provide nimble_password_new and nimble_password_user as extra vars
# $ ansible-playbook -l limit -e nimble_password_new=mynewpass-123 -e nimble_password_user=myusername sample_password_change.yml
- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: password,
        nimble_operation: update }
