---
# Provide nimble_volume as parameter to create and map a block device to a host
# $ ansible-playbook -l limit -e nimble_volume=myvol1 sample_map.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: create }
    - { role: NimbleStorage.Ansinimble, nimble_object: volume, nimble_operation: map }
  tasks:
    - debug:
        var: vars
