---
# Provide nimble_password_new and nimble_password_user as extra vars
# $ ansible-playbook -e nimble_password_new=mynewpass-123
# -e nimble_password_user=myusername
# sample_password_change.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: password,
        nimble_operation: update }
