---
# Deletes a performance policy
# $ ansible-playbook -e nimble_perfpolicy=myperfpol1 \
# sample_perfpolicy_delete.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble, 
        nimble_object: perfpolicy,
        nimble_operation: delete
      }
