---
# Prune volume collections without associated volumes
# $ ansible-playbook sample_volcoll_prune.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volcoll,
        nimble_operation: prune
      }
