---
# Divorce an array from another
#
# $ ansible-playbook -e nimble_partner=mypartner \
# sample_nimble_divorce.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: replication,
        nimble_operation: divorce
      }
