---
# Provide nimble_linux_toolkit_bundle as an extra var to ansible-playbook, i.e:
# $ ansible-playbook -l limit -e nimble_linux_toolkit_bundle=/tmp/nlt_installer-2.0-0 sample_install.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble, nimble_object: nlt, nimble_operation: manage, nimble_linux_toolkit_state: running }
