# Removes NLT from a host
# ansible-playbook sample_uninstall.yml
---
- hosts: myhost1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: nlt,
        nimble_operation: manage,
        nimble_linux_toolkit_state: absent
      }
