---
# Provide nimble_volume and nimble_volume_mountpoint as extra vars, i.e:
# $ ansible-playbook -e nimble_volume=myvol1 \
#   -e nimble_volume_mountpoint=/mnt/myvol1 \
#   -e nimble_host_name=myhost1
#   sample_provision.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: create 
      }
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: map 
      }

- hosts: myhost1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: attach
      }
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: mount 
      }
