---
# Provide nimble_volume and nimble_volcoll OR nimble_protection_template as extra vars, i.e:
# $ ansible-playbook -e nimble_volume=myvol1 \
# -e nimble_protection_template=Retain-30
# sample_protect.yml
# $ ansible-playbook -e nimble_volume=myvol1 \
# -e nimble_volcoll=myexistingvolcoll \
# sample_protect.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: protect,
      }
