---
# Deletes a performance policy
# $ ansible-playbook -l limit -e nimble_perfpolicy=myperfpol1 sample_perfpolicy_delete.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble, 
        nimble_object: perfpolicy,
        nimble_operation: delete
      }
