---
# Provide nimble_volume as parameter to map a block device to a host and attach it
# $ ansible-playbook -e nimble_volume=myvol1 \
# -e nimble_host_name=myhost1
# sample_map.yml

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: map
      }

- hosts: myhost1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: attach
      }
