---
# Provide nimble_volume and nimble_volume_collection OR nimble_protection_template as extra vars, i.e:
# $ ansible-playbook -l limit -e nimble_volume=myvol1 -e nimble_protection_template=Retain-30 sample_protect.yml
# $ ansible-playbook -l limit -e nimble_volume=myvol1 -e nimble_volume_collection=myexistingvolcoll sample_protect.yml

- hosts: all
  roles:
    - { role: NimbleStorage.Ansinimble, 
        nimble_object: volume,
        nimble_operation: protect,
      }
