---
# Provide nimble_volume as parameter to unmap a block device from a host and detach it
# $ ansible-playbook -e nimble_volume=myvol1 \
# -e nimble_host_name=myhost1 \
# sample_unmap.yml

- hosts: myhost1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: detach
      }

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: volume,
        nimble_operation: unmap
      }
