---
# Fetches all facts from an array into nimble_group_facts

- hosts: myarray1
  roles:
    - { role: NimbleStorage.Ansinimble,
        nimble_object: group,
        nimble_operation: facts 
      }
  tasks:
    - debug: 
        var: nimble_group_facts
