---
# Hello World
- hosts: localhost
  become: yes
  vars:
    nimble_folder: smoke-folder
  roles:
    - nimble_host_facts
    - nimble_group_facts
    - nimble_folder_create 

- hosts: localhost
  vars:
    nimble_volume: smoke-volume
    nimble_volume_pool: default
    nimble_volume_perfpolicy: "Windows File Server"
    nimble_volume_folder: smoke-folder
    nimble_folder: smoke-folder
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_create 

# Update folder and create known snapshot
- hosts: localhost
  vars:
    nimble_volume_snapshot: smoke-snap
    nimble_volume: smoke-volume
    nimble_folder: smoke-folder
    nimble_folder_update_options:
      description: "This folder is smoked"
  become: yes
  roles:
    - nimble_group_facts
    - nimble_folder_update
    - nimble_volume_snapshot

# Map & snap
- hosts: localhost
  vars:
    nimble_volume: smoke-volume
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_snapshot

# Create a clone from last snapshot
- hosts: localhost
  vars:
    nimble_volume_from: smoke-volume
    nimble_volume: smoke-clone
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_create

# Whack the clone
- hosts: localhost
  vars:
    nimble_volume: smoke-clone
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete

# Create a clone from a known snapshot
- hosts: localhost
  vars:
    nimble_volume_from: smoke-volume
    nimble_volume: smoke-clone
    nimble_volume_snapshot: smoke-snap
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_create

# Whack the clone
- hosts: localhost
  vars:
    nimble_volume: smoke-clone
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete

# Touch a file
- hosts: localhost
  vars:
    nimble_volume: smoke-volume
  become: yes
  tasks:
    - name: Touch a file
      file:
        path: "/mnt/{{ nimble_volume }}/myfile.txt"
        state: touch

# Unmap/unmount
- hosts: localhost
  vars:
    nimble_volume: smoke-volume
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_umount
    - nimble_volume_unmap

# Restore from last snapshot
- hosts: localhost
  vars:
    nimble_volume: smoke-volume
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_restore
    - nimble_volume_map
    - nimble_volume_mount

- hosts: localhost
  vars: 
    nimble_volume: smoke-volume
  tasks:
    - name: Is the file gone?
      stat:
        path: "/mnt/{{ nimble_volume }}/myfile.txt"
      register: nimble_file
    - debug: var=nimble_file
    - name: Fail if still there
      fail:
        msg: Unable to restore volume
      when: nimble_file.stat.exists

# Prep restore from a known snapshot
- hosts: localhost
  vars:
    nimble_volume: smoke-volume
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_umount
    - nimble_volume_unmap

# Restore from last snapshot
- hosts: localhost
  vars:
    nimble_snapshot: smoke-snap
    nimble_volume: smoke-volume
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_restore
    - nimble_volume_map
    - nimble_volume_mount


# Resize and delete
- hosts: localhost
  vars:
    nimble_folder: smoke-folder
    nimble_volume: smoke-volume
    nimble_volume_size: 30000
  become: yes
  roles:
    - nimble_group_facts
    - nimble_volume_resize
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete
    - nimble_folder_delete
