---
# Hello World
- hosts: smokers
  vars:
    nimble_volume: "{{ inventory_hostname_short }}-vol"
    nimble_volume_pool: default
    nimble_volume_perfpolicy: "Windows File Server"
    nimble_volume_folder: "{{ inventory_hostname_short }}-fldr"
    nimble_folder: "{{ inventory_hostname_short }}-fldr"
  become: yes
  roles:
    - nimble_folder_create 
    - nimble_volume_create 
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_snapshot

# Update folder and a known snap
- hosts: smokers
  vars:
    nimble_folder: "{{ inventory_hostname_short }}-fldr"
    nimble_folder_update_options:
      description: "This folder is smoked"
    nimble_volume: "{{ inventory_hostname_short }}-vol"
    nimble_volume_snapshot: "{{ inventory_hostname_short }}-snap"
  become: yes
  roles:
    - nimble_folder_update
    - nimble_volume_snapshot

# Create a clone from last snapshot
- hosts: smokers
  vars:
    nimble_volume_from: "{{ inventory_hostname_short }}-vol"
    nimble_volume: "{{ inventory_hostname_short }}-cln"
  become: yes
  roles:
    - nimble_volume_create
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete

# Create a clone from a known snapshot
- hosts: smokers
  vars:
    nimble_volume_from: "{{ inventory_hostname_short }}-vol"
    nimble_volume: "{{ inventory_hostname_short }}-cln"
    nimble_volume_snapshot: "{{ inventory_hostname_short }}-snap"
  become: yes
  roles:
    - nimble_volume_create
    - nimble_volume_map
    - nimble_volume_mount
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete

# Touch a file
- hosts: smokers
  vars:
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  become: yes
  tasks:
    - name: Touch a file
      file:
        path: "/mnt/{{ nimble_volume }}/myfile.txt"
        state: touch

# Unmap/unmount
- hosts: smokers
  vars:
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  become: yes
  roles:
    - nimble_volume_umount
    - nimble_volume_unmap

# Restore from last snapshot
- hosts: smokers
  vars:
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  become: yes
  roles:
    - nimble_volume_restore
    - nimble_volume_map
    - nimble_volume_mount

- hosts: smokers
  vars: 
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  tasks:
    - name: Is the file gone?
      stat:
        path: "/mnt/{{ nimble_volume }}/myfile.txt"
      register: nimble_file
    - debug: var=nimble_file
    - name: Fail if still there
      fail:
        msg: Unable to restore volume
      when: nimble_file.stat.exists

# Prep restore from a known snapshot
- hosts: smokers
  vars:
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  become: yes
  roles:
    - nimble_volume_umount
    - nimble_volume_unmap

# Restore from last snapshot
- hosts: smokers
  vars:
    nimble_snapshot: "{{ inventory_hostname_short }}-snap"
    nimble_volume: "{{ inventory_hostname_short }}-vol"
  become: yes
  roles:
    - nimble_volume_restore
    - nimble_volume_map
    - nimble_volume_mount


# Resize and delete
- hosts: smokers
  vars:
    nimble_folder: "{{ inventory_hostname_short }}-fldr"
    nimble_volume: "{{ inventory_hostname_short }}-vol"
    nimble_volume_size: 30000
  become: yes
  roles:
    - nimble_volume_resize
    - nimble_volume_umount
    - nimble_volume_unmap
    - nimble_volume_delete
    - nimble_folder_delete

- hosts: smokers
  become: yes
  tasks:
    - include_role: 
        name: nimble_linux_toolkit
      vars:
        nimble_linux_toolkit_state: absent

