---
- name: Ensure nimble_folder
  fail: msg="Missing variable nimble_folder, please provide a folder name in nimble_folder"
  when: nimble_folder is not defined

- name: Host facts
  include_role:
    name: nimble_host_facts
  when: nimble_host_facts is undefined

- name: Refresh group facts
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_facts:
      volumes:

- name: Get nimble_volume_id
  set_fact:
    nimble_volume_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "volumes[?name=='{{ nimble_volume }}'].id | [0]"

- name: Create snapshot
  uri:
    url: "{{ nimble_group_url }}/snapshots"
    validate_certs: no
    method: POST
    status_code: 201,409 # Ok and exists
    body_format: json
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"
    body:
      data: 
        vol_id: "{{ nimble_volume_id }}"
        name: "{{ nimble_volume_snapshot }}"
    return_content: yes

- name: Refresh volumes
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_fact_refresh:
      volumes:
