---
- name: Ensure play variables are sane
  fail: 
    msg: "Missing variable {{ item }}"
  when: vars[item] is undefined
  with_items:
    - cloud_volume
    - cloud_volume_size
    - cloud_volume_mountpoint

- name: Host facts
  include: cloud_host_facts.yml
  when: cloud_host_facts is undefined

- name: Refresh portal facts
  include: cloud_portal_facts.yml
  vars:
    cloud_portal_facts:
      cloud_volumes: "filters=name={{ cloud_volume }}"

- name: Retrieve Cloud Volume attributes
  include: cloud_volume_attr.yml
  vars:
    local_volume: "{{ cloud_volume }}"

- name: Only allow growing of volumes 
  fail:
    msg: "New size ({{ cloud_volume_size }}) must be greater than old size ({{ cloud_volume_attr.size }})"
  when: cloud_volume_attr.size > cloud_volume_size

- name: Resize Cloud Volume
  uri:
    url: "{{ cloud_portal_api_endpoint }}/cloud_volumes/{{ cloud_volume_id }}"
    validate_certs: yes
    method: PATCH
    status_code: 200,204
    body_format: json
    headers:
      Authorization: "Basic {{ cloud_portal_authz }}"
    body:
      data: 
        size: '{{ cloud_volume_size }}'
    return_content: yes
  when: cloud_volume_id != ''
  retries: "{{ cloud_uri_retries }}"
  delay: "{{ cloud_uri_delay }}"
  register: cloud_volume_resize
  until: cloud_volume_resize | success

- name: Rescan target
  command: iscsiadm -m node -R -T {{ cloud_volume_attr.target_name }}

- name: Reload devmap
  command: multipath -r

- name: Reload devmap (again)
  command: multipath -r
  when: ansible_os_family == 'Debian'

- name: Resize nimble_volume
  command: xfs_growfs {{ cloud_volume_mountpoint | quote }}

- name: Refresh volumes
  include: cloud_portal_facts.yml
  vars:
    cloud_portal_fact_refresh:
      cloud_volumes:
