---
- name: Ensure nimble_folder
  fail: msg="Missing variable nimble_folder, please provide a folder name in nimble_folder"
  when: nimble_folder is not defined

- name: Host facts
  include: nimble_host_facts.yml
  when: nimble_host_facts is undefined

- name: Refresh group facts
  include: nimble_group_facts.yml
  vars:
    nimble_group_facts:
      folders: "fields=name,id&name={{ nimble_folder }}"

- name: Merge options
  set_fact: 
    nimble_folder_update_options_default: "{{ nimble_folder_update_options_default | combine( { item.key: item.value } ) }}"
  with_dict: "{{ nimble_folder_update_options }}"
  when: nimble_folder_update_options is defined

- name: Get nimble_folder_id
  set_fact:
    nimble_folder_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "folders[?name=='{{ nimble_folder }}'].id | [0]"

- name: Update nimble_folder
  uri:
    url: "{{ nimble_group_url }}/folders/{{ nimble_folder_id }}"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data: "{{ nimble_folder_update_options_default }}"
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_folder_updated
  until: nimble_folder_updated | success
