---
- name: Ensure play variables are sane
  fail:
    msg: "Missing variable {{ item }}"
  when: vars[item] is undefined
  with_items:
    - nimble_volume

- name: Refresh group facts
  include: nimble_group_facts.yml
  vars:
    nimble_group_facts:
      volumes: "fields=name,id&name={{ nimble_volume }}"

- include: nimble_util_volume_id.yml

- fail:
    msg: "No such volume {{ nimble_volume }}"
  when: not nimble_volume_id

- name: Merge options
  set_fact:
    nimble_volume_update_options_default: "{{ nimble_volume_update_options_default | combine( { item.key: item.value } ) }}"
  with_dict: "{{ nimble_volume_update_options }}"
  when: nimble_volume_update_options is defined

- name: Update nimble_volume
  uri:
    url: "{{ nimble_group_url }}/volumes/{{ nimble_volume_id }}"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data: "{{ nimble_volume_update_options_default }}"
    headers:
      X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_volume_updated
  until: nimble_volume_updated is success
  when: nimble_volume_update_options_default != {}
