---
- name: Ensure nimble_volume
  fail: msg="Missing variable nimble_volume, please provide a volume name in nimble_volume"
  when: nimble_volume is undefined

- name: Refresh group facts
  include: nimble_group_facts.yml
  vars:
    nimble_group_facts:
      volumes: "fields=name,id&name={{ nimble_volume }}"

- name: Get nimble_volume_id
  set_fact:
    nimble_volume_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "volumes[?name=='{{ nimble_volume }}'].id | [0]"

- name: Offline nimble_volume
  uri:
    url: "{{ nimble_group_url }}/volumes/{{ nimble_volume_id }}?force=true"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data:
        id: "{{ nimble_volume_id }}"
        online: False
    headers:
      X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_volume_offlined
  until: nimble_volume_offlined | success

- name: Delete nimble_volume
  uri:
    url: "{{ nimble_group_url }}/volumes/{{ nimble_volume_id }}"
    validate_certs: no
    method: DELETE
    status_code: 200
    headers:
      X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_volume_deleted
  until: nimble_volume_deleted | success
