---
- name: Ensure nimble_folder
  fail: msg="Missing variable nimble_folder, please provide a folder name in nimble_folder"
  when: nimble_folder is not defined

- name: Refresh group facts
  include: nimble_group_facts.yml
  vars:
    nimble_group_facts:
      folders: "fields=name,id&name={{ nimble_folder }}"

- name: Get nimble_folder_id
  set_fact:
    nimble_folder_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "folders[?name=='{{ nimble_folder }}'].id | [0]"

- name: Delete nimble_folder
  uri:
    url: "{{ nimble_group_url }}/folders/{{ nimble_folder_id }}"
    validate_certs: no
    method: DELETE
    status_code: 200
    headers:
      X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_folder_deleted
  until: nimble_folder_deleted is success
