---
- name: Ensure play variables are sane
  fail:
    msg: "Missing variable {{ item }}"
  when: vars[item] is undefined
  with_items:
    - nimble_protection_template

- name: Group facts
  include: nimble_group_facts.yml
  vars:
    nimble_group_facts:
      protection_templates: "fields=name,id&name={{ nimble_protection_template }}"

- name: Delete protection template
  uri:
    url: "{{ nimble_group_url }}/protection_templates/{{ nimble_group_facts.protection_templates.0.id }}"
    validate_certs: no
    method: DELETE
    status_code: 200
    body_format: json
    headers:
      X-Auth-Token: "{{ nimble_group_token }}"
  retries: "{{ nimble_uri_retries }}"
  delay: "{{ nimble_uri_delay }}"
  register: nimble_prottmpl_deleted
  until: nimble_prottmpl_deleted is success
