---
- name: Generate volume label
  shell: set -o pipefail && echo -n {{ util_volume_label }} | cksum | awk '{ print $1 }'
  args:
    executable: /bin/bash
  register: util_volume_label_generated

- set_fact:
    util_volume_label: "{{ util_volume_label_generated.stdout }}"
