---
- name: Merge options
  set_fact: 
    nimble_folder_update_options_default: "{{ nimble_folder_update_options_default | combine( { item.key: item.value } ) }}"
  with_dict: "{{ nimble_folder_update_options }}"
  when: nimble_folder_update_options is defined

- name: Get nimble_folder_id
  set_fact:
    nimble_folder_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "folders[?name=='{{ nimble_folder }}'].id | [0]"

- name: Update nimble_folder
  uri:
    url: "{{ nimble_group_url }}/folders/{{ nimble_folder_id }}"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data: "{{ nimble_folder_update_options_default }}"
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"

- name: Refresh folders
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_fact_refresh:
      folders:
