---
- name: Merge nimble_initiator_group_options
  set_fact: 
    nimble_initiator_group_options_default: "{{ nimble_initiator_group_options_default | combine( { item.key: item.value } ) }}"
  with_dict: "{{ nimble_initiator_group_options }}"
  when: nimble_initiator_group_options is defined

- name: Create Initiator Group
  uri:
    url: "{{ nimble_group_url }}/initiator_groups"
    validate_certs: no
    method: POST
    status_code: 201
    body_format: json
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"
    body:
     data: "{{ nimble_initiator_group_options_default }}"
    return_content: yes
  register: nimble_initiator_group
  when: nimble_group_facts | json_query(local_query) == []
  vars:
    local_query: "initiator_groups[?name=='{{ nimble_initiator_group_options_default.name }}'].name"

- name: Merge nimble_initiator_options
  set_fact: 
    nimble_initiator_options_default: "{{ nimble_initiator_options_default | combine( { item.key: item.value } ) }}"
  with_dict: "{{ nimble_initiator_options }}"
  when: nimble_initiator_options is defined

- name: Overlay newly created initiator_group ID
  set_fact:
    nimble_initiator_group_id: "{{ nimble_initiator_group.json.data.id }}"
  when: nimble_initiator_group.json.data.id is defined

- name: Find previously created initator_group ID
  set_fact:
    nimble_initiator_group_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "initiator_groups[?name==`{{ inventory_hostname_short }}`].id | [0]"
  when: nimble_initiator_group.json.data.id is undefined

- name: Merge nimble_initiator_group_id
  set_fact:
    nimble_initiator_options_default: "{{ nimble_initiator_options_default | combine( { 'initiator_group_id': nimble_initiator_group_id } ) }}"

- name: Create Initiator
  uri:
    url: "{{ nimble_group_url }}/initiators"
    validate_certs: no
    method: POST
    status_code: 201
    body_format: json
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"
    body:
     data: "{{ nimble_initiator_options_default }}"
    return_content: yes
  when: nimble_group_facts | json_query(local_query) == []
  vars:
    local_query: "initiators[?label=='{{ nimble_initiator_options_default.label }}'].label"

- name: Retrieve nimble_volume_id
  set_fact:
    nimble_volume_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "volumes[?name=='{{ nimble_volume }}'].id | [0]"

- name: Ensure nimble_volume is online
  uri:
    url: "{{ nimble_group_url }}/volumes/{{ nimble_volume_id }}"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data:
        id: "{{ nimble_volume_id }}"
        online: True
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"

- name: Create Access Control Record
  uri:
    url: "{{ nimble_group_url }}/access_control_records"
    validate_certs: no
    method: POST
    status_code: 201, 409
    body_format: json
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"
    body:
     data:
       initiator_group_id: "{{ nimble_initiator_group_id }}"
       vol_id: "{{ nimble_volume_id }}"
    return_content: yes
  when: nimble_group_facts | json_query(local_query) == [] and nimble_volume_id != ''
  vars:
    local_query: "access_control_records[?initiator_group_id=='{{ nimble_initiator_group_id }}' && vol_id=='{{ nimble_volume_id }}'].id"

- name: Refresh objects
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_fact_refresh:
      volumes:
      initiator_groups:
      initiators:
      access_control_records:
