---
- name: Ensure nimble_volume and nimble_volume_mountpoint
  fail: msg="Missing variable nimble_volume and nimble_volume_mountpoint, please provide a volume name in nimble_volume and current mountpoint in nimble_volume_mountpoint"
  when: nimble_volume is not defined and nimble_volume_mountpoint is not defined

- name: Host facts
  include_role:
    name: nimble_host_facts
  when: nimble_host_facts is undefined

- name: Refresh group facts
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_facts:
      volumes:

- name: Retrieve nimble_volume_id
  set_fact:
    nimble_volume_id: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "volumes[?name=='{{ nimble_volume }}'].id | [0]"

- name: Retrieve nimble_volume_target
  set_fact:
    nimble_volume_target: "{{ nimble_group_facts | json_query(local_query) }}"
  vars:
    local_query: "volumes[?name=='{{ nimble_volume }}'].target_name | [0]"

- name: Set new volume size
  uri:
    url: "{{ nimble_group_url }}/volumes/{{ nimble_volume_id }}"
    validate_certs: no
    method: PUT
    status_code: 200
    body_format: json
    body:
      data:
        id: "{{ nimble_volume_id }}"
        size: "{{ nimble_volume_size }}"
    HEADER_X-Auth-Token: "{{ nimble_group_token }}"

- name: Rescan target
  command: iscsiadm -m node -R -T {{ nimble_volume_target }}

- name: Reload devmap
  command: multipath -r

- name: Resize nimble_volume
  command: xfs_growfs {{ nimble_volume_mountpoint }}

- name: Refresh volumes
  include_role:
    name: nimble_group_facts
  vars:
    nimble_group_fact_refresh:
      volumes:
